#ifndef MOODBAR_NATIVE_FFI_H
#define MOODBAR_NATIVE_FFI_H

#pragma once

/* This file is generated by cbindgen. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

enum MoodbarNativeStatus {
  Ok = 0,
  InvalidArgument = 1,
  NotFound = 2,
  Internal = 3,
};
typedef int32_t MoodbarNativeStatus;

typedef struct MoodbarNativeAnalysisSummary {
  uint64_t handle;
  uint32_t frame_count;
  uint32_t channel_count;
} MoodbarNativeAnalysisSummary;

typedef struct MoodbarNativeBuffer {
  uint8_t *ptr;
  size_t len;
  size_t cap;
} MoodbarNativeBuffer;

MoodbarNativeStatus moodbar_native_analysis_from_path(const char *path,
                                                      const char *options_json,
                                                      struct MoodbarNativeAnalysisSummary *out_summary);

MoodbarNativeStatus moodbar_native_analysis_from_bytes(const uint8_t *bytes,
                                                       size_t bytes_len,
                                                       const char *extension,
                                                       const char *options_json,
                                                       struct MoodbarNativeAnalysisSummary *out_summary);

MoodbarNativeStatus moodbar_native_analysis_dispose(uint64_t handle);

MoodbarNativeStatus moodbar_native_render_svg(uint64_t handle,
                                              const char *options_json,
                                              struct MoodbarNativeBuffer *out_svg_utf8);

MoodbarNativeStatus moodbar_native_render_png(uint64_t handle,
                                              const char *options_json,
                                              struct MoodbarNativeBuffer *out_png);

MoodbarNativeStatus moodbar_native_last_error(struct MoodbarNativeBuffer *out_message_utf8);

void moodbar_native_buffer_free(struct MoodbarNativeBuffer *buffer);

#endif  /* MOODBAR_NATIVE_FFI_H */
